// AUTO-GENERATED by scripts/GenRoadmap.java — do not edit by hand.
// Newest series uses /whats-new/; older series use /whats-new/x.y/.

export const releaseSeries = [
  { version: "0.18", label: "0.18.x", href: "/whats-new/" },
  { version: "0.17", label: "0.17.x", href: "/whats-new/0.17/" },
  { version: "0.16", label: "0.16.x", href: "/whats-new/0.16/" },
  { version: "0.15", label: "0.15.x", href: "/whats-new/0.15/" },
  { version: "0.14", label: "0.14.x", href: "/whats-new/0.14/" },
  { version: "0.13", label: "0.13.x", href: "/whats-new/0.13/" },
  { version: "0.12", label: "0.12.x", href: "/whats-new/0.12/" },
  { version: "0.11", label: "0.11.x", href: "/whats-new/0.11/" },
  { version: "0.10", label: "0.10.x", href: "/whats-new/0.10/" },
  { version: "0.9", label: "0.9.x", href: "/whats-new/0.9/" },
] as const;
