// AUTO-GENERATED by scripts/GenRoadmap.java — do not edit by hand.
// Source: Editora's TODO.md. Re-run after the roadmap changes.

export type RoadmapItem = { done: boolean; text: string };
export type RoadmapSection = { title: string; items: RoadmapItem[] };

export const roadmap: RoadmapSection[] = [
  {
    title: "Editing",
    items: [
      { done: true, text: "Smart backspace — clear the indent in one press / jump back on a blank auto-indented line" },
      { done: true, text: "Auto indent" },
      { done: true, text: "Smart indentation" },
      { done: true, text: "Language indentation aware for the 21 languages we support" },
      { done: true, text: "Autoclose <code>()[]{}</code> and quotes" },
      { done: true, text: "Highlight matching braces" },
      { done: true, text: "Comment/uncomment code region" },
      { done: true, text: "Fill paragraph/region (Emacs <code>M-q</code> / Fill Region / <code>C-x f</code> set fill column) — re-wrap to a fill column, preserving indentation + an adaptive fill prefix (line comments, <code>&gt;</code> quotes, Javadoc <code>*</code>)" },
      { done: true, text: "Smart line start (<code>C-a</code>) — first press to the first non-whitespace, second toggles to column 0" },
      { done: true, text: "Markdown formatting — format bar + smart list/heading/link/table editing (see \"Recently shipped\")" },
      { done: true, text: "Format document — <strong>LSP: Format Document</strong> reformats the whole file via the language server (<code>textDocument/formatting</code>, when it advertises formatting), undoable; palette + editor right-click. (GFM table reflow also exists.)" },
      { done: true, text: "Column select support — column/block selection (overlay + column-aware edits)" },
      { done: true, text: "Multiple cursors support — VS Code–style multi-caret (add at next occurrence / above / below) + Alt-drag column selection (personal RichTextFX fork); see \"Recently shipped\"" },
      { done: false, text: "Advanced Undo/Redo support" },
      { done: true, text: "Spell check support — Lucene Hunspell, red squiggles, suggestions, user dictionary, en_US/en_GB" },
      { done: true, text: "Private comments/notes — see <strong>Personal Notes</strong> under \"Recently shipped\"" },
    ],
  },
  {
    title: "Search",
    items: [
      { done: true, text: "Incremental Search — find bar searches as you type (debounced), jumps to the nearest match" },
      { done: true, text: "Regex search — regex + case-sensitive + whole-word toggles in the find bar" },
      { done: true, text: "Multi-file search — Find in Files (<code>C-S-f</code>): project + open buffers, off-thread, with replace-in-files" },
      { done: true, text: "Search results panel — Search Results tool window (<code>M-6</code>), grouped by file, Enter/double-click to jump" },
      { done: true, text: "Find in Files extras — include/exclude globs, query history (editable combo), regex <code>$1</code> replace, ripgrep badge, bold file names, right-side default" },
      { done: true, text: "Highlight all matches — every match highlighted live in the editor (current one accented)" },
      { done: true, text: "AceJump support — <code>M-g j</code>: type a char, then a label, to jump the caret to any on-screen occurrence" },
    ],
  },
  {
    title: "Code intelligence",
    items: [
      { done: true, text: "Autocomplete support — code: snippet popup (Enter/Tab); prose: inline ghost text (Tab); auto + <code>C-M-i</code>/<code>M-/</code> trigger; Settings toggle. (Next: document-words, LSP, fuzzy matching.)" },
      { done: true, text: "LSP support — <strong>21 servers</strong> (see \"Recently shipped\"): diagnostics + Problems window (<code>M-8</code>) + minimap/scrollbar stripes, go-to-definition (<code>M-.</code>), find references (<code>M-?</code>), hover (<code>C-c h</code>), LSP-backed completion, TS/PHP auto-imports, and <strong>Format Document</strong> (whole-file reformat). Server-centric registry, per-server Settings, off by default. Document symbols power the Structure tool window. (Next: format-on-save; rename, code actions, quick fixes.)" },
      { done: true, text: "Fix structure for the 21 languages we support — the Structure tool window now builds from the language server's <code>textDocument/documentSymbol</code> (precise hierarchy, real kinds, per-kind icons, method signatures), with the fold-region/TextMate heuristic as the fallback for non-LSP files; sort (Position/Name/Kind) + kind filter, expanded by default" },
      { done: true, text: "Multi language support — UI string translation (en/it/es/fr/pt/de); see \"UI localization (i18n)\" under \"Recently shipped\"" },
    ],
  },
  {
    title: "Snippets",
    items: [
      { done: false, text: "GUI for Snippet management" },
    ],
  },
  {
    title: "Files & version control",
    items: [
      { done: true, text: "Git support — native CLI (branch/status, gutter change bars, commit workflow, fetch/pull/push)" },
      { done: true, text: "Diff viewer + merge-conflict UI — side-by-side / unified diff (vs HEAD / commit / another file), word-level highlights, apply-hunk / apply-all, patch export, merge-conflict resolver" },
      { done: true, text: "Local file history — IntelliJ-style snapshots on save / auto-save / before an external reload; a <strong>File History</strong> tool window (<code>M-g l</code>) lists revisions (date/time, reason, size; latest tagged *Current*), double-click for a read-only diff vs current, restore = undoable whole-file replace. Gzip'd content-addressed blobs + a per-project index under <code>&lt;configDir&gt;/history/</code>, deduped, with configurable retention (revisions/file, age, size/project). On by default; local-only; off in Simple UI" },
      { done: true, text: "Detect external file changes — prompt to reload when a file changes on disk (focus-regain / tab switch)" },
      { done: true, text: "Auto-reload modified files" },
      { done: true, text: "Remote file editing support — SSH/SFTP: browse/open/edit/save remote files; saved connections (metadata only); local-process features auto-disable for remote (see \"Recently shipped\")" },
      { done: true, text: "Log mode support" },
    ],
  },
  {
    title: "Keybindings",
    items: [
      { done: true, text: "Complete emacs movement/text manipulation keybindings — backward-kill-word (<code>M-DEL</code>), upcase/downcase/capitalize-word + region (<code>M-u</code>/<code>M-l</code>/<code>M-c</code>, <code>C-x C-u</code>/<code>C-x C-l</code>), join-line (<code>M-^</code>), delete-horizontal-space (<code>M-\\</code>), just-one-space (<code>M-SPC</code>), delete-blank-lines (<code>C-x C-o</code>), open-line (<code>C-o</code>), kill-whole-line (<code>C-S-DEL</code>), zap-to-char (<code>M-z</code>), forward/backward-sexp + mark/kill-sexp (<code>C-M-f</code>/<code>C-M-b</code>/<code>C-M-SPC</code>/<code>C-M-k</code>), beginning/end-of-defun (<code>C-M-a</code>/<code>C-M-e</code>), mark-paragraph (<code>M-h</code>), mark-whole-buffer (<code>C-x h</code>), move-to-window-line (<code>M-r</code>). *Kill ring (yank-pop / consecutive-kill accumulation) still deferred.*" },
      { done: true, text: "Fully configurable shortcuts — keybinding editor in Settings → Keymaps: searchable command list, multi-key chord recorder, conflict warnings, per-command + global reset; live (no restart), persisted as overrides on top of the active keymap theme" },
      { done: true, text: "Keybinding themes — switchable in Settings → Keymaps / <code>keymap.select</code>, live (no restart), per-OS (Ctrl vs Cmd): <strong>Emacs</strong> (default), <strong>CUA</strong>, <strong>Sublime Text</strong>, <strong>VSCode</strong>, <strong>IntelliJ IDEA</strong>" },
      { done: false, text: "Vim keybindings (modal — needs a mode state machine: normal/insert/visual, operators, counts, registers, <code>:</code> command line; deferred as its own feature)" },
      { done: true, text: "Standard accelerator commands — <code>edit.selectAll</code> / <code>edit.duplicateLine</code> / <code>edit.moveLineUp</code> / <code>edit.moveLineDown</code>, bound in the CUA/Sublime/VSCode/IntelliJ keymaps" },
    ],
  },
  {
    title: "UI / UX",
    items: [
      { done: false, text: "UI final touches (fonts, colors, etc.)" },
      { done: true, text: "Pretty up Settings Window — sidebar categories, search, live preview, reset" },
      { done: true, text: "File-type icons — a per-type glyph (language logos, image/archive/PDF/table/…, generic fallback) everywhere a file is listed: tabs, Project tree, Open-Files/Recent pickers, Switcher, file/folder finders" },
      { done: true, text: "\"Current Folder\" explorer — with no project open, the Project tool window roots at the active file's folder and follows the focused tab" },
      { done: true, text: "Upgrade breadcrumbs support — _partial:_ Reveal in File Manager / Open Terminal Here on a crumb" },
      { done: true, text: "Fix Zen mode Programming ligatures are OpenType contextual alternates (<code>calt</code>), and JavaFX exposes no feature-control API (no <code>-fx-font-feature-settings</code>, no <code>Font</code> method) — it only auto-shapes complex scripts, never Latin programming ligatures. Even if it did, RichTextFX's editing model maps one char → one glyph cell for caret/selection/hit-testing, which ligature glyph-substitution breaks (the caret lands in the wrong column). Would require both JavaFX feature support *and* ligature-aware caret math in the fork. Deferred unless JavaFX adds OpenType feature control" },
    ],
  },
  {
    title: "Extensibility & integration",
    items: [
      { done: true, text: "Plugins/API support — Java SPI (<code>com.editora.plugin.Plugin</code>) + declarative <code>plugin.json</code> (keymap / external commands / snippet &amp; template dirs); contributes commands, keybindings, tool windows, editor right-click items, and status-bar segments. The <code>ActiveEditor</code> facade does <code>filePath</code>/<code>text</code>/<code>selectedText</code>/<code>caretLine</code>/<code>replaceSelection</code>/<code>insertAtCaret</code>/<code>setText</code>/<code>openPath</code>, and <code>PluginContext</code> adds <code>openUrl</code>/<code>log</code>/<code>setStatus</code> + path accessors. Off by default (Settings → Plugins). Loaded via a child <code>URLClassLoader</code> so it works in the sealed jlink installers. <strong>Registry + install:</strong> browse a curated GitHub-hosted <code>index.json</code>, install (download + SHA-256 verify + zip-slip-guarded unzip) or install from a local <code>.zip</code>; per-plugin Remove. <strong>19 plugins published</strong> in the adriandeleon/editora-plugins registry (which also carries each plugin's source), with 18 worked examples under <code>examples/</code>. <strong>Security:</strong> the index is verified against a bundled <strong>Ed25519 signature</strong> (<code>Settings.pluginRequireSignature</code>, default on, blocks an unsigned/unverified registry; sign with <code>scripts/PluginSigningTool.java</code>); a **capability-disclosure confirm** (jar? external commands? keybinding remaps?) runs before enabling at every arming point; reads are size-bounded and a non-default registry host is flagged. See <code>docs/plugins.md</code>. *Deferred: sandboxing, hot reload, gutter-marker contributions, GitHub-API/per-repo discovery, per-plugin/TOFU signing, auto-update.*" },
      { done: true, text: "External Tools support" },
      { done: true, text: "MCP support — a minimal <strong>Model Context Protocol</strong> server embedded in the editor (loopback HTTP + bearer-token auth) so an LLM agent (Claude Code, …) can observe state + drive the command registry. Six tools: <code>list_open_files</code>, <code>read_buffer</code>, <code>get_diagnostics</code>, <code>find_in_files</code>, <code>list_commands</code>, <code>execute_command</code>; writes <code>&lt;configDir&gt;/mcp-endpoint.json</code> for discovery; status-bar indicator (click to copy the connection command). Off by default behind a security-notice dialog (Settings → MCP Server; <code>view.toggleMcp</code> / <code>mcp.copyEndpoint</code>). No new dependency (<code>jdk.httpserver</code>). (Next: more tools, resources/prompts, stdio transport.)" },
    ],
  },
  {
    title: "Packaging",
    items: [
      { done: false, text: "Sign native installers" },
    ],
  },
];
