// AUTO-GENERATED by scripts/GenRoadmap.java — do not edit by hand.
// Source: Editora's pom.xml <version>. Committed so the build needs no
// access to the Editora repo (it isn't checked out in CI).

export const version = "1.0.0";
