// AUTO-GENERATED by scripts/GenRoadmap.java — do not edit by hand.
// Source: Editora's pom.xml <version> (falling back to the newest released
// CHANGELOG.md section when the pom sits on a -SNAPSHOT/-rc between releases).
// Committed so the build needs no access to the Editora repo (it isn't
// checked out in CI).

export const version = "0.9.8";
