// AUTO-GENERATED by scripts/GenRoadmap.java — do not edit by hand.
// Source: the newest released section of Editora's CHANGELOG.md. Re-run after the changelog changes.

export type NewsItem = { title: string; detail: string };

export const whatsNew: NewsItem[] = [
  { title: "Opening the first file of a language no longer freezes the editor for a beat.", detail: "Starting a language server (forking the jdtls/pyright/tsserver process, scanning <code>PATH</code>, writing the process ledger) ran on the UI thread.…" },
  { title: "Language-server updates aren't sent twice per keystroke.", detail: "After a trigger character (e.g. <code>.</code>), the editor materialized and pushed the whole document to the server both on the completion trigger…" },
  { title: "Editing above a bookmark, note, or breakpoint no longer stutters.", detail: "When an edit shifted a marker's line (e.g. holding Enter above a bookmark), the editor did a blocking…" },
  { title: "The Structure outline no longer rebuilds while it's closed.", detail: "It re-split the whole document and rebuilt its tree on every edit (debounced) even when the tool window was hidden. It now defers the rebuild while…" },
  { title: "The File Information panel no longer slows down typing.", detail: "It re-counted words (a whole-document scan) on every caret move and re-materialized the whole document on every keystroke — even when the panel was…" },
  { title: "Zooming text is much smoother.", detail: "A text zoom (<code>Ctrl</code>+wheel, <code>Ctrl</code>+<code>=</code>/<code>-</code>/<code>0</code>, the status-bar <code>−/+</code>) reran the…" },
  { title: "Moving the caret or typing in a large file is much lighter.", detail: "The status bar recomputed the file size — which scans and copies the whole document — on every caret move and keystroke (and re-materialized the…" },
  { title: "Bookmarks and Personal Notes now group by project, so they don't appear/disappear when you switch projects.", detail: "Each panel always shows the General (no-project) group and the current project, and a new \"Show all projects\" toggle reveals every other project's…" },
];
