// AUTO-GENERATED by scripts/GenRoadmap.java — do not edit by hand.
// Source: the newest released section of Editora's CHANGELOG.md. Re-run after the changelog changes.

export type NewsItem = { title: string; detail: string };

export const whatsNew: NewsItem[] = [
  { title: "Project-tree folders", detail: "Can be compared recursively with HEAD, a branch, a tag, or a selected revision. The lazy multi-file review is scoped to that folder and includes…" },
  { title: "<code>editora --diff-ui LEFT RIGHT</code>", detail: "Now opens an isolated, session-free diff workspace with only the comparison UI visible. A full-UI icon in the diff toolbar restores normal Editora…" },
  { title: "Side-by-side diffs", detail: "Now draw JetBrains-style change ribbons between related hunks, with a compact right-edge overview track for changes across the full document." },
  { title: "The diff viewer", detail: "Now opens multi-file patches as one navigable review with per-file statistics; supports exact, trimmed, or ignored-whitespace matching, context…" },
  { title: "The Commit tool window and command palette", detail: "Can open all staged files or all unstaged/untracked files as one repository review, with per-file status, statistics, navigation, and the usual Git…" },
  { title: "Recursive folder comparison", detail: "Now scans off-thread and opens only changed, left-only, or right-only files in a lazy multi-file review. It is available from the VCS menu, command…" },
  { title: "Editable local comparisons", detail: "Can open a syntax-highlighted Result draft below the diff. Draft changes re-diff after a short idle delay and apply to the real editor as one…" },
  { title: "The VCS menu and command palette can compare clipboard or empty text with the active…", detail: "The VCS menu and command palette can compare clipboard or empty text with the active file. Every full diff can swap left and right sides without…" },
];
