// AUTO-GENERATED by scripts/GenRoadmap.java — do not edit by hand.
// Source: the newest released section of Editora's CHANGELOG.md. Re-run after the changelog changes.

export type NewsItem = { title: string; detail: string };

export const whatsNew: NewsItem[] = [
  { title: "Per-project settings you can commit", detail: "a project can carry <code>.editora/settings.toml</code> saying which language server to run and whether to run it, overriding your global preferences…" },
  { title: "New Project From Template", detail: "scaffold a whole project and open it in its own window, rather than pointing Editora at a folder you made yourself. Pick a multi-file template, fill…" },
  { title: "Long-running work now says it's running", detail: "a find-in-files sweep over a big tree used to announce itself once and then go quiet, which looks identical to a hang. The status bar now shows…" },
  { title: "Failures no longer slip past you", detail: "the status bar shows one message at a time and the next one replaces it, so an error that appeared while you were typing used to vanish without…" },
  { title: "Rename now shows you what it will change", detail: "a rename that reaches beyond the current file lists every affected file first, with its change count and where it moves to, and you can untick any…" },
  { title: "Run configurations gain a before-launch step, and can be shared with your team", detail: "a configuration can name a command to run first (a build, a codegen step); a non-zero exit aborts the launch, so a stale binary is never run by…" },
  { title: "A run-configuration selector in the toolbar", detail: "pick a saved configuration and hit Run or Debug, with Stop beside them; the choice is remembered across restarts. Each configuration also becomes a…" },
  { title: "A menu bar", detail: "File / Edit / Find / View / Navigate / Code / Run / VCS / Tools / Window / Help, so the things Editora can do are <em>browsable</em> rather than only…" },
];
