#!/usr/bin/env python3
"""Generate src/lib/commands.ts from the app's real sources:
   - command ids from MainController.registerCommands()
   - titles from i18n messages.properties (command.<id>)
   - keys from every bundled keymap (emacs/cua/sublime/vscode/intellij) — the
     base (Win/Linux, Ctrl) variant; macOS substitutes Cmd. `keys` stays the
     Emacs chord (default keymap); `bindings` carries the chord per keymap.
Re-run after commands or bindings change:  python3 website/scripts/gen-commands.py
"""
import re, json, os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "commands.ts")

mc = open(os.path.join(ROOT, "src/main/java/com/editora/ui/MainController.java")).read()
ids = sorted(set(re.findall(r'Command\.of\("([^"]+)"', mc)))

props = {}
for line in open(os.path.join(ROOT, "src/main/resources/com/editora/i18n/messages.properties"), encoding="utf-8"):
    line = line.rstrip("\n")
    if line.startswith("command.") and "=" in line:
        k, v = line.split("=", 1)
        props[k[len("command."):]] = v

# Every bundled keymap, in display order (id, label). Base (Win/Linux) files; macOS swaps Cmd.
KEYMAPS = [
    ("emacs", "Emacs"),
    ("cua", "CUA"),
    ("sublime", "Sublime Text"),
    ("vscode", "VS Code"),
    ("intellij", "IntelliJ IDEA"),
]

# key_for_km[kmId][commandId] = first chord that keymap binds to the command.
key_for_km = {}
for kid, _ in KEYMAPS:
    data = json.load(open(os.path.join(ROOT, f"src/main/resources/com/editora/keymaps/{kid}.json")))
    d = {}
    for chord, cmd in data.items():
        d.setdefault(cmd, chord)
    key_for_km[kid] = d

# Legacy: `keys` is the Emacs (default keymap) chord, used by the Commands page.
key_for = key_for_km["emacs"]

ORDER = [
    "Files", "Editing", "Navigation", "Search", "Buffers & tabs",
    "View & display", "Folding", "Splits & zoom", "Markdown",
    "Code intelligence (LSP)", "Run", "Debugging", "Git & diff",
    "HTTP client", "Diagrams", "Bookmarks", "Personal notes",
    "Snippets & templates", "Projects", "Remote (SFTP)", "Spell check",
    "Appearance", "Tool windows", "Window", "Application",
]

def category(cid):
    p = cid.split(".")[0]
    if cid in ("editor.exportPdf", "editor.print", "preview.exportPdf", "preview.print"):
        return "Files"
    if cid in ("file.run", "file.runWithArgs"):
        return "Run"
    if p in ("file", "recent"):
        return "Files"
    if p == "edit":
        return "Editing"
    if p == "nav":
        return "Navigation"
    if p in ("find", "search"):
        return "Search"
    if p in ("buffer", "switcher"):
        return "Buffers & tabs"
    if p == "markdown" or cid.startswith("view.markdown") or p == "preview" or cid == "view.toggleMarkdownPreviewTheme":
        return "Markdown"
    if cid in ("view.fold", "view.foldAll", "view.unfold", "view.unfoldAll", "view.toggleFold"):
        return "Folding"
    if cid in ("view.splitHorizontal", "view.splitVertical", "view.unsplit",
               "view.textZoomIn", "view.textZoomOut", "view.textZoomReset"):
        return "Splits & zoom"
    if cid in ("view.settings", "view.welcome", "view.messageLog", "view.debugLog"):
        return "Application"
    if p == "view":
        return "View & display"
    if p in ("git", "diff", "merge"):
        return "Git & diff"
    if p == "debug":
        return "Debugging"
    if p == "lsp":
        return "Code intelligence (LSP)"
    if p == "http":
        return "HTTP client"
    if p == "mermaid":
        return "Diagrams"
    if p == "run":
        return "Run"
    if p == "bookmarks":
        return "Bookmarks"
    if p == "notes":
        return "Personal notes"
    if p in ("snippets", "template"):
        return "Snippets & templates"
    if p == "project":
        return "Projects"
    if p == "remote":
        return "Remote (SFTP)"
    if p == "spell":
        return "Spell check"
    if p == "theme":
        return "Appearance"
    if p == "tool":
        return "Tool windows"
    if p == "window":
        return "Window"
    return "Application"

# Descriptions come straight from i18n: command.<id>.desc (English base), the single
# source of truth shared with the app's command palette. `props` already parsed them as
# "<id>.desc" → text above; see DESC_OF below.
def desc_of(cid):
    return props.get(cid + ".desc", "")

def js(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

groups = {g: [] for g in ORDER}
for cid in ids:
    groups[category(cid)].append(cid)

lines = []
lines.append("// AUTO-GENERATED by website/scripts/gen-commands.py — do not edit by hand.")
lines.append("// Sources: MainController.registerCommands(), messages.properties, keymaps/*.json.")
lines.append("// Re-run the script after commands or keybindings change.")
lines.append("")
lines.append("// `keys` is the Emacs (default) chord; `bindings` maps each keymap id to its chord")
lines.append("// (base Win/Linux variant — macOS substitutes Cmd). Only keymaps that bind it appear.")
lines.append("export type Cmd = { title: string; id: string; keys?: string; bindings?: Record<string, string>; desc?: string };")
lines.append("export type CmdGroup = { title: string; commands: Cmd[] };")
lines.append("")
lines.append("export const keymaps: { id: string; name: string }[] = [")
for kid, label in KEYMAPS:
    lines.append(f'  {{ id: "{js(kid)}", name: "{js(label)}" }},')
lines.append("];")
lines.append("")
lines.append("export const commandGroups: CmdGroup[] = [")
for g in ORDER:
    if not groups[g]:
        continue
    lines.append("  {")
    lines.append(f'    title: "{js(g)}",')
    lines.append("    commands: [")
    for cid in groups[g]:
        title = js(props.get(cid, cid))
        key = key_for.get(cid, "")
        desc = js(desc_of(cid))
        parts = [f'title: "{title}"', f'id: "{cid}"']
        if key:
            parts.append(f'keys: "{js(key)}"')
        binds = []
        for kid, _ in KEYMAPS:
            c = key_for_km[kid].get(cid)
            if c:
                binds.append(f'"{kid}": "{js(c)}"')
        if binds:
            parts.append("bindings: { " + ", ".join(binds) + " }")
        if desc:
            parts.append(f'desc: "{desc}"')
        lines.append("      { " + ", ".join(parts) + " },")
    lines.append("    ],")
    lines.append("  },")
lines.append("];")
lines.append("")
lines.append("export const commandCount = commandGroups.reduce(")
lines.append("  (n, g) => n + g.commands.length,")
lines.append("  0,")
lines.append(");")
lines.append("")

open(OUT, "w").write("\n".join(lines))
total = sum(len(v) for v in groups.values())
print(f"Wrote {OUT}: {total} commands in {sum(1 for g in ORDER if groups[g])} groups")
